name: steve
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python=3.7.4
    - eli5=0.10.1
    - imbalanced-learn=0.6.2
    - pysam=0.15.4
    - PyVCF=0.6.8
    - scikit-learn=0.22.2.post1
    - scikit-optimize=0.7.4
    - snakemake=5.11.1
    - xgboost=1.0.2
